"""界面文字（中英双语），导入时合并进 simplequant.i18n.TEXT"""

from simplequant.i18n import TEXT, L

TEXT.update({
    # ---- 导航 ----
    "nav.home": L("首页", "Home"),
    "nav.data": L("1. 数据", "1. Data"),
    "nav.strategy": L("2. 策略", "2. Strategy"),
    "nav.backtest": L("3. 回测", "3. Backtest"),
    "nav.optimize": L("4. 参数优化", "4. Optimize"),
    "nav.go_data": L("前往数据页", "Go to Data"),
    "nav.go_strategy": L("前往策略页", "Go to Strategy"),
    "nav.go_backtest": L("前往回测", "Go to Backtest"),
    "nav.go_optimize": L("前往参数优化", "Go to Optimize"),

    # ---- 首页 ----
    "home.title": L("SimpleQuant 量化回测", "SimpleQuant Backtester"),
    "home.subtitle": L("无需编程，即可完成 A 股及 ETF 策略的回测与评估。回测引擎：Backtrader",
                       "Backtest and evaluate A-share and ETF strategies without programming. Engine: Backtrader"),
    "home.s1": L("1. 准备数据", "1. Get data"),
    "home.s1_body": L("通过 AKShare、BaoStock 免费获取日线及分钟线数据，或导入自有的 CSV、快照及 Tick 数据。",
                      "Obtain free daily and intraday bars from AKShare and BaoStock, or import your own CSV, snapshot or tick data."),
    "home.s1_note": L("本地已有 {n} 份数据", "{n} datasets stored locally"),
    "home.s2": L("2. 搭建策略", "2. Build a strategy"),
    "home.s2_body": L("支持调整内置模板参数、以条件组件组合交易规则、用自然语言描述由 AI 生成，或直接编写 Python 代码。",
                      "Tune a built-in template, combine rules from condition blocks, describe the strategy in plain language for AI to generate, or write Python code."),
    "home.s2_note": L("已保存 {n} 个策略", "{n} strategies saved"),
    "home.s3": L("3. 回测", "3. Backtest"),
    "home.s3_body": L("选择数据与策略，设置初始资金与交易费用，即可获得收益、回撤及买卖点等完整结果。",
                      "Select data and a strategy, set capital and trading costs, and obtain returns, drawdowns and trade markers."),
    "home.s3_note": L("按 A 股规则撮合：整手交易、T+1、印花税、最低佣金",
                      "A-share rules: 100-share lots, T+1, stamp duty, minimum commission"),
    "home.s4": L("4. 参数优化", "4. Optimize"),
    "home.s4_body": L("对参数网格进行批量回测，通过热力图识别稳健的参数区间，并以样本外数据检验是否存在过拟合。",
                      "Backtest a grid of parameters, identify robust regions on a heatmap, and test for overfitting on out-of-sample data."),
    "home.s4_note": L("多进程并行，最多 500 组参数", "Parallel processing, up to 500 combinations"),
    "home.sources": L("免费数据源对比", "Free data sources compared"),
    "home.sources_table": L("""
| 数据源 | 频率 | 适用场景 |
|---|---|---|
| **AKShare** | 日线 | ETF、股票、指数日线，支持复权，推荐优先使用 |
| **BaoStock** | 日线、5/15/30/60 分钟 | 股票分钟线（约自 2000 年起）；ETF 分钟线仅覆盖近期 |
| **通达信本地文件** | 日线、1/5 分钟 | 需先在通达信客户端执行「盘后数据下载」，再由本软件读取；免费且稳定 |
| **CSV 导入** | 任意 | 自有数据；含 `last` 列的快照或 Tick 数据将自动合成为 K 线 |
""", """
| Source | Frequency | Best for |
|---|---|---|
| **AKShare** | Daily | Daily ETF, stock and index bars with price adjustment. Recommended default |
| **BaoStock** | Daily, 5/15/30/60 min | Stock intraday bars (from about 2000); ETF intraday data covers recent periods only |
| **TDX local files** | Daily, 1/5 min | Download after-hours data in the TDX client first, then read it here. Free and reliable |
| **CSV import** | Any | Your own data; snapshots or ticks with a `last` column are converted into bars |
"""),

    # ---- 通用 ----
    "src.akshare": L("AKShare", "AKShare"),
    "src.baostock": L("BaoStock", "BaoStock"),
    "src.tdx_local": L("通达信本地", "TDX local"),
    "src.csv": L("CSV 导入", "CSV import"),
    "exp.button": L("导出 Python 脚本", "Export Python script"),
    "exp.help": L("导出可独立运行的 Python 脚本（仅依赖 backtrader、pandas 及数据源库），包含当前的数据设置、策略与费率，成交结果与本软件回测完全一致。本地或 CSV 数据将读取同名 CSV 文件（可在数据页下载）。",
                  "Exports a standalone Python script (requiring only backtrader, pandas and the data library) with the current data settings, strategy and costs; its fills match this backtest exactly. Local or CSV data is read from a CSV file of the same name (available on the Data page)."),
    "exp.menu": L("导出策略", "Export"),
    "exp.platform_note": L("导出至量化平台：交易信号与本软件回测一致；由于各平台的复权方式与成交细节不同，收益可能存在小幅偏差。使用说明见文件开头。",
                           "For quant platforms: signals match this backtest. Because each platform adjusts prices and fills orders differently, returns may differ slightly. Instructions are at the top of each file."),
    "exp.daily_only": L("导出至量化平台目前仅支持日线数据", "Platform export supports daily data only"),
    "exp.help_joinquant": L("聚宽：免费注册后即可在网页端回测，无需券商账户。请新建股票策略并粘贴全部内容。",
                            "JoinQuant: free registration, backtesting in the browser, no brokerage account required. Create a new stock strategy and paste the entire file."),
    "exp.help_myquant": L("掘金量化：免费注册，安装掘金终端及 gm 库后在本地运行回测，无需券商账户。",
                          "MyQuant: free registration; install the terminal and the gm package to run backtests locally. No brokerage account required."),
    "exp.help_qmt": L("迅投 QMT：需使用已开通 QMT 权限的券商账户。文件采用 GBK 编码，可直接导入 QMT 策略编辑器；仅在回测模式下执行下单。",
                      "QMT: requires a brokerage account with QMT access. The file is GBK-encoded for direct import into the QMT editor and places orders in backtest mode only."),
    "exp.help_selection":L("导出调用 SimpleQuant 引擎的脚本，用于更新数据、执行回测并保存最新选股结果，可定时运行。可使用 SimpleQuant 的 Python 环境运行，或通过本菜单的「运行选股脚本」执行。",
                            "Exports a script that uses the SimpleQuant engine to update data, run the backtest and save the latest picks; can be scheduled. Run it with the SimpleQuant Python environment or with \"Run selection script\" in this menu."),
    "exp.run_script": L("运行选股脚本…", "Run selection script…"),
    "exp.run_script_help": L("选择此前导出的选股脚本，由 SimpleQuant 直接运行（无需安装 Python）：更新数据、执行回测，并保存成交记录及最新选股结果",
                             "Pick a previously exported selection script and run it inside SimpleQuant (no Python needed): updates data, backtests and saves orders and the latest picks"),
    "exp.run_title": L("运行选股脚本", "Run selection script"),
    "exp.run_pick": L("选择导出的 .py 文件", "Choose an exported .py file"),
    "exp.run_bad": L("该文件不是 SimpleQuant 导出的选股脚本", "This is not a selection script exported by SimpleQuant"),
    "exp.run_running": L("正在运行 {name}（首次运行需更新数据，可能需要数分钟）…", "Running {name} (the first run updates data and may take a few minutes)…"),
    "exp.run_done": L("运行完成，结果保存在：", "Finished. Results saved in:"),
    "exp.run_failed": L("运行出错，详见上方日志", "The script failed; see the log above"),
    "exp.open_folder": L("打开文件夹", "Open folder"),
    "gui.close": L("关闭", "Close"),
    "exp.sel_platform_note": L("导出至量化平台：由平台使用其自身的成分股、行情及估值数据，按相同算法选股，可持续向后运行。由于数据口径存在差异，处于入选边界附近的股票可能互换。日志将输出每期与本软件名单的重合数量。",
                               "For quant platforms: stocks are selected on the platform with its own constituents, prices and valuations using the same algorithm, so the strategy can keep running forward. Because data sources differ, stocks near the cut-off may swap. The log reports how many picks overlap with this backtest each period."),
    "exp.sel_follow": L("按 SimpleQuant 名单调仓", "Follow SimpleQuant's picks"),
    "exp.sel_follow_help": L("不在平台上计算因子，而是直接写入本软件回测得出的各期名单，平台仅负责调仓。支持全部因子，但回测仅能进行至数据截止日。适用于单独对比成交、费用及分红处理。",
                             "Writes this backtest's picks into the file so the platform only rebalances. Supports every factor, but can only run up to the end of the data. Useful for comparing fills, costs and dividend handling in isolation."),
    "exp.sel_need_run": L("请先以当前设置运行回测，名单方可写入文件；未运行时仍可导出「平台计算」版本，但无法核对重合数量。",
                          "Run the backtest with the current settings to include its picks. Without it, the platform version can still be exported, but without the overlap check."),
    "lib.download_csv": L("下载 CSV", "Download CSV"),
    "prov.eastmoney": L("东方财富", "Eastmoney"),
    "prov.sina": L("新浪·不复权", "Sina · unadjusted"),
    "adj.hfq": L("后复权", "Back-adjusted"),
    "adj.qfq": L("前复权", "Forward-adjusted"),
    "adj.none": L("不复权", "Unadjusted"),

    # ---- 数据页 ----
    "data.tab_download": L("在线下载", "Download"),
    # ---- 利率与信用利差 ----
    "rates.title": L("利率与信用利差", "Rates and credit spreads"),
    "rates.note": L("来自中债收益率曲线（{year} 年起）：10 年期国债收益率、期限利差（10 年 − 1 年）、信用利差（3 年期 AAA 中短期票据 − 3 年期国债）。"
                    "下载后可在策略的规则条件中使用（「利率/信用利差」分组），例如信用利差走阔时卖出。首次下载约 2–3 分钟，数据量很小。",
                    "From the ChinaBond yield curves (since {year}): 10-year government yield, term spread (10Y − 1Y) and credit "
                    "spread (3Y AAA medium-term notes − 3Y government). Once downloaded, they can be used in rule conditions "
                    "(the \"Rates / credit spread\" group), e.g. sell when credit spreads widen. The first download takes 2–3 minutes and is small."),
    "rates.status": L("已有 {start} ~ {end}；最新：10 年国债 {cgb}%，期限利差 {term} BP，信用利差 {credit} BP",
                      "Have {start} ~ {end}; latest: 10Y {cgb}%, term spread {term} bp, credit spread {credit} bp"),
    "rates.none": L("尚未下载", "Not downloaded yet"),
    "rates.update": L("下载 / 更新利率数据", "Download / update rates"),
    "rates.done": L("利率数据已更新", "Rates updated"),
    "rates.need": L("规则用到了利率或信用利差，请先在「数据」页下载利率数据", "The rule uses rates or credit spreads; download rates on the Data page first"),
    "data.tab_csv": L("导入 CSV", "Import CSV"),
    "data.tab_library": L("本地数据库", "Local library"),
    "data.source": L("数据源", "Data source"),
    "data.popular": L("常用标的", "Popular symbols"),
    "data.other_codes": L("其他代码（6 位，以逗号分隔）", "Other codes (6 digits, comma-separated)"),
    "data.other_codes_ph": L("例如：600519, 000001", "e.g. 600519, 000001"),
    "data.freq": L("K 线周期", "Bar size"),
    "data.adjust": L("复权方式", "Price adjustment"),
    "data.adjust_help": L("回测建议使用后复权数据，以避免分红除权造成的价格失真",
                          "Back-adjusted prices are recommended for backtests to avoid distortions from dividends and splits"),
    "data.start": L("开始日期", "Start date"),
    "data.end": L("结束日期", "End date"),
    "data.asset": L("品种类型", "Asset type"),
    "data.tdx_dir": L("通达信安装目录（包含 vipdoc 文件夹）", "TDX installation folder (containing vipdoc)"),
    "data.force": L("忽略本地已有数据，重新下载", "Ignore local data and download again"),
    "data.download": L("下载至本地数据库", "Download to local library"),
    "data.fetching": L("正在获取 {sym}…", "Fetching {sym}…"),
    "data.fetched": L("{sym}：{n} 根 K 线（{start} ~ {end}）", "{sym}: {n} bars ({start} ~ {end})"),
    "data.fetch_failed": L("{sym} 获取失败", "Failed to fetch {sym}"),
    "data.csv_intro": L("支持两类文件：**K 线**（包含日期及开、高、低、收、量列，列名可为中文或英文）与**快照 / Tick**（包含 `last` 最新价列，将合成为 K 线）。",
                        "Two file types are supported: **bars** (a date column plus open/high/low/close/volume, with Chinese or English headers) and **snapshots/ticks** (with a `last` price column, converted into bars)."),
    "data.file_source": L("文件来源", "File source"),
    "data.file_upload": L("上传文件", "Upload files"),
    "data.file_path": L("本机路径（适用于大文件或整个文件夹）", "Local path (for large files or entire folders)"),
    "data.choose_csv": L("选择 CSV 文件", "Choose CSV files"),
    "data.path": L("文件或文件夹路径", "File or folder path"),
    "data.folder_files": L("该文件夹内共有 {n} 个 CSV 文件，将合并为一份数据", "{n} CSV files in this folder will be merged into one dataset"),
    "data.path_missing": L("路径不存在", "Path does not exist"),
    "data.is_snapshot": L("已识别为**快照 / Tick** 数据", "Detected **snapshot/tick** data"),
    "data.is_kline": L("已识别为 **K 线**数据", "Detected **bar** data"),
    "data.resample_to": L("合成 K 线周期", "Build bars of"),
    "data.resample_opt": L("重新合成周期（可选）", "Resample to (optional)"),
    "data.keep": L("保持不变", "Keep as is"),
    "data.name": L("数据名称", "Dataset name"),
    "data.import": L("导入至本地数据库", "Import to local library"),
    "data.importing": L("正在读取并整理数据…", "Reading and cleaning data…"),
    "data.imported": L("已导入 {n} 根 K 线（{start} ~ {end}）", "Imported {n} bars ({start} ~ {end})"),
    "data.import_failed": L("导入失败：{e}", "Import failed: {e}"),
    "data.empty": L("暂无数据，请通过「在线下载」或「导入 CSV」添加。", "No data yet. Add data via Download or Import CSV."),
    "lib.name": L("名称", "Name"),
    "lib.freq": L("周期", "Bar size"),
    "lib.source": L("来源", "Source"),
    "lib.adjust": L("复权", "Adjustment"),
    "lib.start": L("开始", "Start"),
    "lib.end": L("结束", "End"),
    "lib.rows": L("K 线数", "Bars"),
    "lib.updated": L("更新时间", "Updated"),
    "lib.preview": L("预览", "Preview"),
    "lib.delete": L("删除此数据", "Delete this dataset"),

    # ---- 策略页 ----
    "strat.mode": L("搭建方式", "Build method"),
    "strat.mode_template": L("策略模板（调整参数）", "Template (tune parameters)"),
    "strat.mode_rule": L("条件组件（自定义规则）", "Condition blocks (custom rules)"),
    "strat.pick_template": L("选择模板", "Template"),
    "strat.preset": L("从示例开始（将覆盖当前规则）", "Start from an example (replaces current rules)"),
    "strat.load_preset": L("载入示例", "Load example"),
    "strat.buy_title": L("买入条件（空仓时检查）", "Buy conditions (checked when flat)"),
    "strat.sell_title": L("卖出条件（持仓时检查）", "Sell conditions (checked when holding)"),
    "strat.position": L("买入资金比例（%）", "Capital used per buy (%)"),
    "strat.position_help": L("选择多个标的时，资金按标的数量平均分配", "Split evenly when several assets are selected"),
    "strat.indicator": L("指标", "Indicator"),
    "strat.line": L("输出线", "Line"),
    "strat.compare": L("比较方式", "Comparison"),
    "strat.right": L("比较对象", "Right side"),
    "strat.right_ind": L("指标", "Indicator"),
    "strat.right_value": L("数值", "Value"),
    "strat.delete_cond": L("删除此条件", "Delete this condition"),
    "strat.logic": L("逻辑", "Logic"),
    "strat.no_sell": L("未设置卖出条件：买入后将持有至回测结束", "No sell conditions: positions are held until the end of the backtest"),
    "strat.add_cond": L("添加条件", "Add condition"),
    "strat.preview": L("策略预览", "Strategy preview"),
    "strat.name": L("策略名称", "Strategy name"),
    "strat.name_ph": L("例如：沪深300 双均线", "e.g. CSI 300 SMA cross"),
    "strat.save": L("保存", "Save"),
    "strat.saved": L("已保存「{name}」", "Saved \"{name}\""),
    "strat.to_backtest": L("使用此策略回测", "Backtest this strategy"),
    "strat.unnamed": L("未命名策略", "Untitled strategy"),
    "strat.saved_list": L("已保存的策略（{n}）", "Saved strategies ({n})"),
    "strat.load": L("载入", "Load"),
    "strat.delete": L("删除", "Delete"),
    "preset.ma": L("双均线金叉死叉", "SMA golden / death cross"),
    "preset.macd": L("MACD 金叉 + 8% 止损", "MACD cross + 8% stop loss"),
    "preset.breakout": L("突破 20 日新高", "20-day high breakout"),
    "preset.rsi": L("RSI 超卖反弹 + 5% 止损", "RSI oversold rebound + 5% stop loss"),
    "preset.boll": L("布林带下轨买入", "Buy at lower Bollinger band"),

    # ---- 回测页 ----
    "bt.no_data": L("本地暂无数据，请先在「1. 数据」页面下载或导入。",
                    "No local data yet. Please download or import data on the \"1. Data\" page first."),
    "bt.data": L("数据", "Data"),
    "bt.pick_assets": L("选择标的（可多选，多个标的时资金平均分配）", "Assets (multiple selections split capital evenly)"),
    "bt.mixed_freq": L("所选数据的 K 线周期不一致，请选择相同周期的数据",
                       "The selected datasets have different bar sizes. Please select datasets with the same bar size"),
    "bt.no_overlap": L("所选数据不存在重叠的时间区间", "The selected datasets do not overlap in time"),
    "bt.range": L("回测区间", "Date range"),
    "bt.strategy": L("策略", "Strategy"),
    "bt.pick_strategy": L("选择策略", "Strategy"),
    "bt.opt_current": L("当前策略：{name}", "Current: {name}"),
    "bt.opt_saved": L("已保存：{name}", "Saved: {name}"),
    "bt.opt_template": L("模板（默认参数）：{name}", "Template (defaults): {name}"),
    "bt.edit_strategy": L("编辑或新建策略", "Edit or create a strategy"),
    "bt.costs": L("资金与交易成本", "Capital & trading costs"),
    "bt.cash": L("初始资金（元）", "Initial capital (CNY)"),
    "bt.cost_preset": L("费率预设", "Cost preset"),
    "bt.t1": L("T+1（按品种执行）", "T+1 (by product type)"),
    "bt.t1_help": L("开启时，股票及境内股票 ETF 当日买入、次日方可卖出；债券 ETF、可转债、货币 ETF、黄金 ETF、商品期货 ETF、"
                    "跨境 ETF 实行 T+0，不受此限制。品种根据代码和名称自动判断。关闭时全部按 T+0 处理",
                    "When on, stocks and domestic equity ETFs bought today can only be sold from the next day; bond, "
                    "convertible, money-market, gold, commodity-futures and cross-border ETFs are T+0 and exempt. "
                    "The product type is inferred from the code and name. When off, everything is treated as T+0"),
    "bt.t0_assets": L("以下标的实行 T+0，当日买入当日即可卖出：{names}",
                      "These assets are T+0 and can be sold on the day they are bought: {names}"),
    "bt.dividend": L("分红处理", "Dividends"),
    "bt.div_reinvest": L("分红再投资", "Reinvest"),
    "bt.div_cash": L("现金分红", "Cash"),
    "bt.dividend_help": L(
        "分红再投资：直接使用所选数据（后复权数据下分红全额再投资、不扣税，与多数回测软件一致）。\n"
        "现金分红：根据不复权价及分红送转数据重新计算行情（等比复权），信号不受除权除息影响；"
        "除息日现金到账，保留在账户中直至下次买入；股票卖出时按持股期限扣缴红利税（≤1 个月 20%，1 个月至 1 年 10%，超过 1 年免税），"
        "个人持有 ETF 所获分红免税。首次使用需联网下载不复权行情及分红数据，之后将缓存于本机。\n"
        "注意：东方财富的后复权采用加法复权，长期收益略低于等比复权，因此两种方式的差异并非全部来自分红。",
        "Reinvest: use the selected data as-is (with back-adjusted data, dividends are fully reinvested and untaxed, like most backtesters).\n"
        "Cash: prices are rebuilt from unadjusted bars plus dividend data (proportional adjustment), so signals are unaffected by ex-dates; "
        "cash arrives on the ex-date and stays in the account until the next purchase; for stocks, dividend tax is deducted on sale by "
        "holding period (≤1 month 20%, ≤1 year 10%, over 1 year exempt); ETF dividends are tax-free for individuals. "
        "Downloads unadjusted bars and dividend data (cached afterwards).\n"
        "Note: Eastmoney's back-adjustment is additive and slightly understates long-run returns compared with proportional "
        "adjustment, so not all of the difference between the two options comes from dividends."),
    "bt.unadjusted": L("{names} 为不复权数据：除权除息日价格下跳，可能产生虚假的卖出信号，且分红不计入收益。"
                       "建议改用后复权数据，或在「资金与交易成本」中选择「现金分红」。",
                       "{names}: unadjusted data. Prices drop on ex-dates, which can trigger false sell signals, and dividends "
                       "are not counted. Use back-adjusted data, or choose \"Cash\" dividends under Capital & trading costs"),
    "bt.chip_cash_div": L("现金分红", "cash dividends"),
    "cd.skipped": L("以下标的无法使用现金分红，仍按所选数据计算（分红再投资）：{items}",
                    "These assets could not use cash dividends and are computed from the selected data (dividends reinvested): {items}"),
    "cd.patched": L("分红数据中缺失的现金分红已根据复权价推算补齐：{items}",
                    "Cash dividends missing from the dividend data were inferred from the adjusted prices: {items}"),
    "cd.reason_source": L("CSV 等导入数据无法识别品种", "imported data such as CSV has no known asset type"),
    "cd.reason_index": L("指数不分红", "indexes pay no dividends"),
    "cd.reason_no_dividends": L("分红数据下载失败", "dividend data could not be downloaded"),
    "cd.reason_no_unadjusted": L("不复权行情下载失败，或与所选数据不一致", "unadjusted bars could not be downloaded or do not match the selected data"),
    "cd.reason_mismatch": L("存在分红数据以外的除权（如份额折算、配股）", "corporate actions not in the dividend data (e.g. share splits, rights issues)"),
    "bt.cost_detail": L("费率明细", "Cost details"),
    "bt.commission": L("佣金费率（万分之）", "Commission (bps)"),
    "bt.min_comm": L("最低佣金（元）", "Minimum commission (CNY)"),
    "bt.stamp": L("卖出印花税（万分之）", "Stamp duty on sells (bps)"),
    "bt.slippage": L("滑点（万分之）", "Slippage (bps)"),
    "bt.need_assets": L("该策略至少需要 {n} 个标的", "This strategy requires at least {n} assets"),
    "bt.run": L("开始回测", "Run backtest"),
    "bt.running": L("正在回测…", "Running backtest…"),
    "bt.failed": L("运行失败：{e}", "Run failed: {e}"),
    "bt.results": L("回测结果", "Results"),
    "bt.excess": L("超额 {v}", "Excess {v}"),
    "bt.show_trades_for": L("查看买卖点", "Show trades for"),
    "bt.tab_orders": L("成交记录", "Fills"),
    "bt.tab_trades": L("完整交易", "Round trips"),
    "bt.tab_logs": L("运行日志", "Log"),
    "bt.no_orders": L("未产生任何成交。请检查买入条件是否过于严格，或回测区间是否过短。",
                      "No fills. Check whether the buy conditions are too strict or the date range is too short."),
    "bt.download_orders": L("下载成交记录（CSV）", "Download fills (CSV)"),
    "help.benchmark": L("所选标的等权买入并持有", "Equal-weight buy & hold of the selected assets"),
    "help.trades": L("一次买入与对应的卖出计为一笔交易", "One buy and its matching sell count as one trade"),
    "help.profit_factor": L("盈利交易总额 ÷ 亏损交易总额", "Gross profit ÷ gross loss"),

    # ---- 图表 ----
    "chart.equity": L("资产曲线（元）", "Equity (CNY)"),
    "chart.drawdown": L("回撤", "Drawdown"),
    "chart.strategy": L("策略", "Strategy"),
    "chart.benchmark": L("基准（等权买入持有）", "Benchmark (equal-weight buy & hold)"),
    "chart.close": L("收盘价", "close"),

    # ---- 参数优化页 ----
    "opt.intro": L("对策略中的数值参数进行网格搜索：每组参数执行一次完整回测，并通过热力图识别表现稳定的参数区域。",
                   "Grid-search the numeric parameters of a strategy: each combination runs a full backtest, and a heatmap shows which regions perform consistently well."),
    "opt.params": L("待优化参数（最多 3 个）", "Parameters to optimize (up to 3)"),
    "opt.pick_params": L("选择参数", "Parameters"),
    "opt.current": L("当前值 {v}", "current {v}"),
    "opt.from": L("起始值", "From"),
    "opt.to": L("终止值", "To"),
    "opt.step": L("步长", "Step"),
    "opt.target": L("优化目标", "Optimize for"),
    "opt.oos": L("样本外检验数据占比（%）", "Out-of-sample hold-out (%)"),
    "opt.oos_help": L("仅在前段数据上寻找最优参数，再以末段数据进行检验。若样本外表现明显变差，表明参数存在过拟合。",
                      "Parameters are selected on the earlier data only and then tested on this final portion. Significantly worse out-of-sample results indicate overfitting."),
    "opt.workers": L("并行进程数", "Parallel workers"),
    "opt.workers_help": L("同时运行的回测数量，建议设为 CPU 核心数减一", "Number of backtests run simultaneously; CPU cores minus one is recommended"),
    "opt.too_many": L("共 {n} 组参数，超过上限 {max}，请缩小范围或增大步长", "{n} combinations exceeds the limit of {max}. Narrow the ranges or increase the steps"),
    "opt.combos": L("共 {n} 组参数", "{n} combinations"),
    "opt.run": L("开始优化", "Run optimization"),
    "opt.progress": L("回测进度 {done}/{n}", "Backtesting {done}/{n}"),
    "opt.results": L("优化结果", "Optimization results"),
    "opt.split_caption": L("样本内 {start} ~ {cut}　|　样本外 {cut} ~ {end}", "In-sample {start} ~ {cut}  |  Out-of-sample {cut} ~ {end}"),
    "opt.failed_combos": L("{n} 组参数运行失败，已跳过", "{n} combinations failed and were skipped"),
    "opt.best": L("最优", "Best"),
    "opt.in_sample": L("样本内", "in-sample"),
    "opt.robustness": L("样本外检验", "Out-of-sample check"),
    "opt.col_is_best": L("样本内 · 最优参数", "In-sample · best params"),
    "opt.col_oos_best": L("样本外 · 最优参数", "Out-of-sample · best params"),
    "opt.col_oos_orig": L("样本外 · 原参数", "Out-of-sample · original params"),
    "opt.overfit": L("最优参数在样本外表现明显下降，可能存在过拟合。建议在热力图中选择整体表现良好的区域，而非单个最高点。",
                     "The best parameters perform significantly worse out of sample, which suggests overfitting. Prefer a region of the heatmap that performs well overall rather than a single peak."),
    "opt.robust_ok": L("样本外表现与样本内基本一致。", "Out-of-sample performance is broadly consistent with in-sample."),
    "opt.landscape": L("参数表现分布", "Parameter landscape"),
    "opt.x_axis": L("横轴", "X axis"),
    "opt.y_axis": L("纵轴", "Y axis"),
    "opt.fix": L("固定 {name}", "Fix {name} at"),
    "opt.heatmap_hint": L("红色越深表示表现越好，绿色越深表示越差，加框的格子为最优值。连片的红色区域比孤立的最高点更为可靠。",
                          "Deeper red indicates better results and deeper green worse; the outlined cell is the best. A broad red region is more reliable than an isolated peak."),
    "opt.top": L("前 {n} 名参数组合", "Top {n} combinations"),
    "opt.save_name": L("保存为策略", "Save as strategy"),
    "opt.tuned": L("优化后", "tuned"),
    "opt.use_best": L("以最优参数回测", "Backtest with best parameters"),

    # ---- 交互式策略图 ----
    "chart.trade_pnl": L("每笔交易盈亏", "Trade P&L"),
    "chart.volume": L("成交量", "Volume"),
    "chart.r1m": L("1月", "1M"),
    "chart.r3m": L("3月", "3M"),
    "chart.r6m": L("6月", "6M"),
    "chart.r1y": L("1年", "1Y"),
    "chart.rall": L("全部", "All"),
    "bt.strategy_chart_note": L("拖动可缩放，双击可复原；鼠标悬停时显示各栏当日数值；点击图例可隐藏对应曲线。虚线为条件中使用的阈值及常用参考线。",
                                "Drag to zoom and double-click to reset; hover to show each panel's values for that day; click legend items to hide lines. Dotted lines mark thresholds used in the conditions and common reference levels."),

    # ---- Backtrader 原生图 ----
    "nat.tab": L("Backtrader 原生图", "Backtrader chart"),
    "nat.note": L("Backtrader 内置图表：包含 K 线、成交量、买卖点、策略所用的各项指标（各占一栏）、资金变化及每笔交易盈亏，便于查看指标在何处触发交易。该图为静态图片，时间跨度越短越清晰。",
                  "Backtrader's built-in chart: candles, volume and trade markers, every indicator the strategy uses (one panel each), account value and the P&L of each trade. Useful for seeing where indicators triggered trades. It is a static image; shorter ranges are easier to read."),
    "nat.range": L("显示区间", "Range to show"),
    "nat.range_help": L("回测仍从数据起始日运行（确保指标与持仓准确），仅绘制该区间，最多 {n} 根 K 线", "The backtest still runs from the start of the data (so indicators and positions are accurate); only this range is drawn, up to {n} bars"),
    "nat.draw": L("生成图表", "Draw chart"),
    "nat.drawing": L("正在绘图…", "Drawing…"),
    "nat.download": L("下载 PNG", "Download PNG"),

    # ---- 滚动优化 ----
    "wf.mode": L("优化方式", "Method"),
    "wf.mode_grid": L("普通优化", "Standard"),
    "wf.mode_wf": L("滚动优化（Walk-forward）", "Walk-forward"),
    "wf.mode_help": L("普通优化基于全部历史数据选取参数，结果通常偏乐观；滚动优化仅使用过去的数据选取参数，并在随后的时段检验，逐段向前推进，得到完全样本外的表现，更接近实际使用情况。",
                      "Standard optimization selects parameters using the entire history, which tends to be optimistic. Walk-forward selects them from past data only, tests them on the following period and rolls forward, producing fully out-of-sample results that better reflect real use."),
    "wf.settings": L("滚动设置", "Walk-forward settings"),
    "wf.train": L("训练期（月）", "Training (months)"),
    "wf.train_help": L("每次选取参数时使用的历史数据长度", "Length of history used to select parameters each time"),
    "wf.test": L("测试期（月）", "Testing (months)"),
    "wf.test_help": L("选出的参数使用多长时间后重新优化（即每段样本外的长度）", "How long selected parameters are used before re-optimizing (the length of each out-of-sample segment)"),
    "wf.window": L("窗口方式", "Window"),
    "wf.window_rolling": L("滚动（训练期长度固定）", "Rolling (fixed length)"),
    "wf.window_anchored": L("锚定（自最早数据起逐步延长）", "Anchored (from the start, expanding)"),
    "wf.window_help": L("滚动窗口能更快适应市场变化；锚定窗口使用的数据更多，参数更稳定", "Rolling windows adapt faster to changing markets; anchored windows use more data and produce steadier parameters"),
    "wf.stitch": L("参数切换时", "When parameters change"),
    "wf.stitch_continuous": L("延续持仓", "Keep positions"),
    "wf.stitch_restart": L("每段重新开始", "Restart each segment"),
    "wf.stitch_help": L("延续持仓：视新参数一直在运行，持仓状态延续（切换参数时的调仓成本略有低估）。每段重新开始：每个测试期从空仓开始，资金逐段延续，期末按全部卖出扣除成本——结果更保守，但趋势策略会错过正在进行的行情。",
                        "Keep positions: new parameters are treated as if they had been running all along, so positions carry over (switching costs are slightly understated). Restart: each test period starts flat with the carried-over capital and is charged a full sell at the end. This is more conservative, but trend strategies miss moves already under way."),
    "wf.no_windows": L("数据长度不足一个训练期加一个测试期，请缩短训练期或延长回测区间。", "Not enough data for one training period plus one testing period. Shorten the training period or extend the date range."),
    "wf.too_many": L("共需 {n} 次回测，超过上限 {max}，请缩小参数范围、增大步长或延长测试期", "{n} backtests exceeds the limit of {max}. Narrow the ranges, increase the steps or lengthen the testing period"),
    "wf.estimate": L("将划分为 {w} 个窗口，共约 {n} 次回测", "{w} windows, about {n} backtests"),
    "wf.run": L("开始滚动优化", "Run walk-forward"),
    "wf.progress": L("窗口 {w}/{n}", "Window {w}/{n}"),
    "wf.results": L("滚动优化结果（均为样本外）", "Walk-forward results (all out of sample)"),
    "wf.caption": L("{n} 个窗口 · 样本外 {start} ~ {end} · 参数切换时：{stitch}", "{n} windows · out of sample {start} ~ {end} · on parameter change: {stitch}"),
    "wf.oos_return": L("样本外总收益", "Out-of-sample return"),
    "wf.vs_base": L("较原参数 {v}", "{v} vs original"),
    "wf.wfe": L("滚动效率 WFE", "WFE"),
    "wf.wfe_help": L("样本外年化收益 ÷ 训练期（样本内）平均年化收益。通常认为 50% 以上表明参数在未来仍基本有效；过低或为负则表明优化主要在拟合历史噪声。",
                     "Out-of-sample annualized return ÷ average in-sample annualized return. Above about 50% generally indicates the parameters remain broadly effective; very low or negative values indicate the optimization is mainly fitting past noise."),
    "wf.verdict_good": L("滚动效率良好，且样本外表现不逊于始终使用原参数：该调参方法在历史上有效。",
                         "WFE is reasonable and out-of-sample results are no worse than keeping the original parameters: this tuning approach has been effective historically."),
    "wf.verdict_bad": L("样本外表现明显逊于样本内或始终使用原参数的结果：频繁调参在历史上未带来收益，参数可能在拟合噪声。建议考虑固定参数或延长训练期。",
                        "Out-of-sample results fall well short of in-sample results or of keeping the original parameters: re-tuning has not added value historically and may be fitting noise. Consider fixed parameters or a longer training period."),
    "wf.chart_equity": L("样本外资产曲线（元）", "Out-of-sample equity"),
    "wf.line_wf": L("滚动优化", "Walk-forward"),
    "wf.line_base": L("始终使用原参数", "Original parameters"),
    "wf.note_continuous": L("灰色虚线表示参数切换时点。拼接方式：延续持仓——各段使用选出的参数自训练期起点运行，仅取测试期收益，切换参数时的调仓成本略有低估。",
                            "Dotted lines mark parameter changes. Stitching: keep positions. Each segment runs its parameters from the start of training and only the test-period returns are used; switching costs are slightly understated."),
    "wf.note_restart": L("灰色虚线表示参数切换时点。拼接方式：每段重新开始——每个测试期从空仓开始，期末按全部卖出扣除佣金、印花税及滑点。",
                         "Dotted lines mark parameter changes. Stitching: restart. Each test period starts flat and is charged commission, stamp duty and slippage for a full sell at the end."),
    "wf.stability": L("参数稳定性", "Parameter stability"),
    "wf.stability_note": L("各窗口选出的参数。若参数频繁大幅变动，表明最优参数不稳定，通常意味着过拟合。", "Parameters selected in each window. Large, frequent changes indicate an unstable optimum, usually a sign of overfitting."),
    "wf.windows": L("各窗口明细", "Windows"),
    "wf.col_train_start": L("训练开始", "Train start"),
    "wf.col_train_end": L("训练结束", "Train end"),
    "wf.col_test_start": L("测试开始", "Test start"),
    "wf.col_test_end": L("测试结束", "Test end"),
    "wf.col_train_metric": L("训练期{m}", "Train {m}"),
    "wf.col_test_return": L("测试期收益", "Test return"),
    "wf.col_test_cagr": L("测试期年化", "Test CAGR"),
    "wf.col_test_max_drawdown": L("测试期最大回撤", "Test max DD"),

    # ---- 因子 ----
    "lib.factors": L("包含因子列：{cols}", "Factor columns: {cols}"),
    "lib.no_factors": L("不含估值或换手率因子列（通过 BaoStock 下载股票日线可获得换手率、PE、PB、PS）",
                        "No valuation or turnover columns (download stock daily data from BaoStock to obtain turnover, P/E, P/B and P/S)"),
    "bt.lot_too_big": L("{names}：出现买入信号，但资金不足以买入一手（100 股），因此未成交。建议提高初始资金，或改用前复权 / 不复权数据——后复权价格可能远高于实际成交价，会高估一手所需资金。",
                        "{names}: buy signals occurred, but the capital was insufficient for one 100-share lot, so no shares were bought. Increase the initial capital, or use forward-adjusted or unadjusted data: back-adjusted prices can be far above actual trading prices and overstate the cost of a lot."),
    "bt.missing_factor": L("「{name}」缺少 {cols} 数据，相关条件将始终无法满足。建议改用 BaoStock 下载股票日线。",
                           "\"{name}\" has no {cols} data, so the related conditions will never be met. Download stock daily data from BaoStock instead."),

    # ---- 代码编辑 ----
    "strat.mode_code": L("编写代码（Python）", "Write code (Python)"),
    "strat.to_code": L("转换为代码编辑", "Edit as code"),
    "strat.to_code_help": L("将当前策略转换为等价的 Python 代码并放入代码编辑区，可修改任意细节",
                            "Convert this strategy into equivalent Python code in the code editor, where any detail can be changed"),
    "code.start_from": L("起始内容（将覆盖编辑区中的代码）", "Start from (replaces the code in the editor)"),
    "code.start_skeleton": L("空白示例（含注释的双均线策略）", "Blank example (commented SMA cross)"),
    "code.start_template": L("模板 · {name}", "Template · {name}"),
    "code.start_rule": L("当前条件组件", "Current condition blocks"),
    "code.load": L("载入", "Load"),
    "code.intro": L("请编写一个 class Strategy，继承 PerAsset（资金在各标的间平均分配）或 BaseStrategy（自行管理资金）。"
                    "整手交易、T+1、手续费及成交记录均与其他策略一样由系统处理。代码在本机运行，权限与普通 Python 程序相同。",
                    "Write a class Strategy derived from PerAsset (capital split evenly across assets) or BaseStrategy "
                    "(capital managed by your code). Lots, T+1, fees and fill records are handled by the system as for any other strategy. "
                    "The code runs on this computer with the same permissions as any Python program."),
    "code.cheatsheet": L("可用工具", "Available tools"),
    "code.check": L("检查代码", "Check code"),
    "code.check_ok": L("代码检查通过", "Code check passed"),
    "code.params": L("已识别的参数（可在「参数优化」页调整）：{names}", "Parameters found (tunable on the Optimize page): {names}"),
    "code.no_params": L("代码中未定义 params，参数优化页将没有可调整的参数", "No params are defined in the code, so there is nothing to tune on the Optimize page"),

    # ---- AI 写策略 ----
    "strat.mode_ai": L("自然语言描述（AI）", "Describe in plain language (AI)"),
    "ai.need_config": L("请先配置大模型接口（支持 Claude、OpenAI、DeepSeek、通义千问、本地 Ollama 等）。",
                        "Please configure a model first (Claude, OpenAI, DeepSeek, Qwen, local Ollama and others are supported)."),
    "ai.examples": L("示例", "Examples"),
    "ai.describe": L("描述买卖规则", "Describe your buy and sell rules"),
    "ai.placeholder": L("例如：MACD 金叉且 RSI 低于 70 时买入，死叉或亏损超过 8% 时卖出，仓位 80%",
                        "e.g. Buy when MACD crosses up and RSI is below 70; sell on the cross down or an 8% loss; use 80% of capital"),
    "ai.generate": L("生成策略", "Generate strategy"),
    "ai.thinking": L("AI 正在分析…", "Analyzing…"),
    "ai.understood": L("AI 解析结果（请核对）", "AI interpretation (please verify)"),
    "ai.unsupported": L("以下要求暂无法以规则表达，已忽略：", "The following requests cannot yet be expressed as rules and were omitted:"),
    "ai.symbols": L("提及的标的：{codes}", "Symbols mentioned: {codes}"),
    "ai.symbols_missing": L("（{codes} 尚未下载，请前往「1. 数据」页面获取）", "({codes} not yet downloaded; obtain them on the \"1. Data\" page)"),
    "ai.edit_in_builder": L("在条件组件中编辑", "Edit in condition blocks"),
    "ai.no_result": L("描述策略后点击「生成策略」，生成的规则将显示在此处。", "Describe a strategy and click \"Generate strategy\"; the generated rules will appear here."),
    "ai.explain": L("AI 解读结果", "Explain with AI"),
    "ai.explain_note": L("以上内容由 AI 生成，仅供参考，不构成投资建议。", "AI-generated content for reference only; not investment advice."),
    "ai.ex1_short": L("MACD 金叉 + 止损", "MACD cross + stop loss"),
    "ai.ex1": L("MACD 金叉且 RSI 低于 70 时买入；MACD 死叉或亏损超过 8% 时卖出，仓位 80%",
                "Buy when MACD crosses up and RSI is below 70; sell when MACD crosses down or the loss exceeds 8%; use 80% of capital"),
    "ai.ex2_short": L("放量突破", "Volume breakout"),
    "ai.ex2": L("收盘价突破 20 日新高且成交量明显放大时买入，跌破 10 日最低价时卖出",
                "Buy when the close breaks the 20-day high on a significant volume increase; sell when it falls below the 10-day low"),
    "ai.ex3_short": L("KDJ 低位金叉", "KDJ low golden cross"),
    "ai.ex3": L("KDJ 的 K 值低于 20 且 K 上穿 D 时买入，J 值大于 100 时卖出，止损 5%",
                "Buy when KDJ K is below 20 and K crosses above D; sell when J is above 100; 5% stop loss"),
    "ai.ex4_short": L("低估值 + 高活跃度", "Low valuation + high activity"),
    "ai.ex4": L("市盈率低于 15 且换手率大于 1% 时买入，市盈率高于 30 或盈利达到 20% 时卖出",
                "Buy when P/E is below 15 and turnover is above 1%; sell when P/E is above 30 or the gain reaches 20%"),

    # ---- 多因子选股 ----
    "nav.selection": L("5. 多因子选股", "5. Stock selection"),
    "nav.go_selection": L("前往多因子选股", "Go to Stock selection"),
    "home.s5": L("5. 多因子选股", "5. Multi-factor selection"),
    "home.s5_body": L("在沪深300、中证500等指数成分股或全部可转债中，按价值、动量、低波动、双低等因子评分选股；先以 IC 与分层回测检验因子有效性，再进行定期调仓回测。",
                      "Score CSI 300 and CSI 500 constituents or all convertible bonds on value, momentum, low volatility, double-low and other factors; validate each factor with IC and quantile analysis, then backtest a periodically rebalanced portfolio."),
    "home.s5_note": L("采用历史成分股，避免幸存者偏差", "Uses historical index constituents to avoid survivorship bias"),
    "sp.intro": L("在指数成分股或全部可转债中按因子评分，定期买入得分最高的一组。建议先在「因子研究」中确认因子有效，再于「选股回测」中组合使用。",
                  "Score index constituents or all convertible bonds on factors and periodically buy the top-scoring group. Validate each factor in Factor research first, then combine factors in Backtest."),
    "sp.universe": L("股票池", "Universe"),

    # ---- 可转债（选股页的「可转债（全市场）」股票池） ----
    "cb.total": L("可转债总数", "Convertible bonds"),
    "cb.total_help": L("含已退市的转债（2007 年起），用于避免幸存者偏差", "Includes delisted bonds since 2007, to avoid survivorship bias"),
    "cb.downloaded": L("已下载日线", "With daily data"),
    "cb.downloaded_help": L("起始日之后仍在交易的转债", "Bonds still trading after the start date"),
    "cb.trading": L("目前在交易", "Trading now"),
    "cb.as_of": L("数据截至", "Data through"),
    "cb.start_help": L("在此之前已退市的转债不下载。2018 年以前转债数量较少", "Bonds delisted before this date are skipped. There were few convertibles before 2018"),
    "cb.workers_help": L("同时下载的连接数。新浪接口频繁访问会被暂时封禁，程序已自动限速，建议设为 3",
                         "Number of simultaneous downloads. Requests to Sina are rate-limited automatically; 3 is recommended"),
    "cb.download_note": L("数据来源：东方财富（转债列表、条款、纯债价值与转股价值）、新浪财经（日线）、中证指数公司（中证转债指数）。"
                          "首次下载约 1000 只、约 40 MB，需 6–10 分钟；此后仅更新仍在交易的转债。",
                          "Sources: Eastmoney (bond list, terms, bond floor and conversion value), Sina Finance (daily bars), "
                          "China Securities Index (CSI Convertible Bond Index). The first download covers about 1,000 bonds "
                          "(about 40 MB) and takes 6–10 minutes; later updates fetch only bonds still trading."),
    "cb.step_list": L("正在获取转债列表…", "Fetching the bond list…"),
    "cb.step_info": L("条款", "Terms"),
    "cb.step_index": L("正在获取中证转债指数…", "Fetching the CSI Convertible Bond Index…"),
    "cb.step_daily": L("日线", "Daily bars"),
    "cb.download_done": L("可转债数据已更新", "Convertible bond data updated"),
    "cb.rules": L("回测规则说明", "Backtest rules"),
    "cb.rules_text": L(
        "- **每手 10 张**，T+0；默认使用债券费率（佣金万分之 0.5，无印花税），可在下方修改\n"
        "- **涨跌幅**：2022-08-01 起为 ±20%，上市首日为 +57.3% / −43.3%（相对面值 100 元）；此前无涨跌幅限制\n"
        "- **强赎与到期**：发布强制赎回或到期赎回公告的转债，公告当日起不再入选，下一个交易日开盘卖出持仓；"
        "因停牌、违约、正股退市等意外停止交易的，当时无法预知，持仓按最后价格保留、无法卖出（与实际一致）\n"
        "- **付息**：转债按全价交易，付息日价格下跳。回测按条款中的票面利率计入税后利息（扣 20% 个人所得税），"
        "与股票的后复权口径相同（利息再投资）\n"
        "- **数据缺口**：个别转债缺少上市初期的新浪日线，这些交易日只用东方财富的收盘价计算因子，不进行交易\n"
        "- **未模拟**：转股、回售、下修博弈；正股停牌、退市对转债的影响以实际成交价格体现\n"
        "- 可转债开户有投资者适当性要求（2022 年起：前 20 个交易日日均资产不低于 10 万元，且具有 2 年以上证券交易经验）",
        "- **Lot of 10 bonds**, T+0; bond commissions by default (0.005%, no stamp duty), editable below\n"
        "- **Price limits**: ±20% from 2022-08-01, +57.3% / −43.3% of par on the first trading day; no limits before\n"
        "- **Calls and maturity**: once a forced-redemption or maturity notice is published the bond is no longer "
        "selected and holdings are sold at the next open; bonds that stop trading unexpectedly (suspension, default, "
        "stock delisting) cannot be sold and stay at their last price, as in reality\n"
        "- **Coupons**: convertibles trade at full price and drop on coupon dates; coupons from the bond terms are added "
        "after 20% tax and reinvested, like back-adjusted stock prices\n"
        "- **Data gaps**: a few bonds lack Sina bars for their first months; those days use Eastmoney closes for factors "
        "only and are not traded\n"
        "- **Not simulated**: conversion, put options and reset plays\n"
        "- Trading convertibles requires investor suitability (since 2022: 100k CNY average assets and 2 years of "
        "trading experience)"),
    "cb.neutral_size_help": L("剔除因子中的发行规模成分，避免因子仅成为小规模转债的替代",
                              "Removes issue-size effects so the factor is not merely a small-bond proxy"),
    "cb.empty_no_limit": L("。清空表示不限", ". Leave empty for no limit"),
    "cb.coupon_note": L("付息：按税后利息再投资计入（与股票后复权口径相同），详见「数据」标签页的回测规则说明。",
                        "Coupons are reinvested after tax (like back-adjusted stock prices); see Backtest rules on the Data tab."),
    "cb.top_n": L("持有转债数", "Number of bonds"),
    "cb.bench_label": L("基准（中证转债指数）", "Benchmark (CSI Convertible Bond Index)"),
    "sp.tab_data": L("数据", "Data"),
    "sp.tab_research": L("因子研究", "Factor research"),
    "sp.tab_backtest": L("选股回测", "Backtest"),
    "sp.tab_wf": L("滚动优化", "Walk-forward"),
    "sp.tab_custom": L("自定义因子", "Custom factors"),

    # ---- 自定义因子 ----
    "cf.intro": L("使用 Python 编写函数 factor(p)，返回「日期 × 股票」的因子值表。保存后，该因子将出现在因子研究、选股回测、"
                  "滚动优化的因子列表中（分组为「自定义」），模拟盘亦可使用。代码在本机运行，权限与普通 Python 程序相同。",
                  "Write a Python function factor(p) that returns a dates × stocks table of factor values. Once saved, it "
                  "appears in the factor lists for research, backtest and walk-forward (group \"Custom\") and can be used "
                  "in paper trading. The code runs on this computer with the same permissions as any Python program."),
    "cf.none": L("暂无自定义因子", "No custom factors yet"),
    "cf.saved": L("已保存的自定义因子（{n}）", "Saved custom factors ({n})"),
    "cf.edit": L("编辑", "Edit"),
    "cf.new": L("新建", "New"),
    "cf.name": L("因子名称", "Factor name"),
    "cf.name_ph": L("例如：20 日乖离率", "e.g. 20-day MA deviation"),
    "cf.desc": L("说明（可选）", "Description (optional)"),
    "cf.direction_help": L("默认方向：选股时因子值越大越好或越小越好（可在选股回测中修改）",
                           "Default direction: whether higher or lower values are better (can be changed in the backtest)"),
    "cf.editing": L("正在编辑「{name}」", "Editing \"{name}\""),
    "cf.creating": L("新建因子", "New factor"),
    "cf.trial": L("试算", "Trial run"),
    "cf.trial_help": L("在当前股票池及区间上试算，查看覆盖率、IC 及分组收益（无需先保存）",
                       "Compute it on the current universe and period to view coverage, IC and quantile returns (saving is not required)"),
    "cf.trial_title": L("试算结果（持有 20 天，分 5 组）", "Trial result (20-day horizon, 5 groups)"),
    "cf.coverage": L("覆盖率", "Coverage"),
    "cf.coverage_help": L("可选股票中具有因子值的比例", "Share of eligible stocks with a factor value"),
    "cf.low_coverage": L("超过半数股票缺少因子值（NaN），选股时将被排除。请检查滚动窗口是否过长，或所用字段是否需要财务数据。",
                         "More than half of the stocks have no value (NaN) and will be excluded. Check whether the rolling "
                         "window is too long or whether the fields require financial data."),
    "cf.direction_hint": L("IC 的符号与所设默认方向相反，该因子反向使用可能效果更好。",
                           "The IC sign is opposite to the default direction; the factor may perform better in the reverse direction."),
    "cf.need_name": L("请先填写因子名称", "Please enter a factor name first"),
    "cf.delete_confirm": L("确定删除自定义因子「{name}」？使用该因子的已保存选股策略将无法运行。",
                           "Delete custom factor \"{name}\"? Saved selection strategies that use it will no longer run."),
    "cf.cheatsheet": L("""p["close"]  p["open"]  p["high"]  p["low"]        # 后复权价格；均为 日期 × 股票 的表
p["volume"]  p["amount"]  p["turnover"]  p["pct_chg"]   # 成交量、成交额、换手率(%)、涨跌幅(%)
p["pe"]  p["pb"]  p["ps"]                             # 估值（TTM / MRQ）
p["roe"]  p["gross_margin"]  p["net_margin"]  p["np_yoy"]  p["rev_yoy"]  p["mcap"]
                                                     # 财务字段：需先在「数据」标签页下载财务数据
# 可转债（股票池选「可转债（全市场）」时）：
p["raw_close"]  p["premium"]  p["bond_premium"]  p["double_low"]   # 不复权价、转股溢价率(%)、纯债溢价率(%)、双低
p["conv_value"]  p["bond_value"]  p["conv_price"]  p["stock_close"]  # 转股价值、纯债价值、转股价、正股价
p["remain_years"]  p["issue_size"]                  # 剩余期限（年）、发行规模（亿元）

x.shift(5)                       # 5 日前的值（仅可向前回看，请勿使用 shift(-n)）
x.rolling(20, min_periods=15).mean() / .std() / .max()
x.pct_change(20, fill_method=None)
x.rank(axis=1, pct=True)         # 每日在全部股票中的排名（0~1）
np.log(x)  x.where(x > 0)  x.clip(lower, upper)
# 去极值与标准化由系统统一处理，无需自行实现""",
                       """p["close"]  p["open"]  p["high"]  p["low"]        # back-adjusted prices; each is a dates × stocks table
p["volume"]  p["amount"]  p["turnover"]  p["pct_chg"]   # volume, value traded, turnover (%), change (%)
p["pe"]  p["pb"]  p["ps"]                             # valuation (TTM / MRQ)
p["roe"]  p["gross_margin"]  p["net_margin"]  p["np_yoy"]  p["rev_yoy"]  p["mcap"]
                                                     # financial fields: download financial data on the Data tab first
# Convertible bonds (universe "Convertible bonds (all)"):
p["raw_close"]  p["premium"]  p["bond_premium"]  p["double_low"]   # raw price, conversion premium (%), premium over bond floor (%), double-low
p["conv_value"]  p["bond_value"]  p["conv_price"]  p["stock_close"]  # conversion value, bond floor, conversion price, stock price
p["remain_years"]  p["issue_size"]                  # years to maturity, issue size (100M CNY)

x.shift(5)                       # value 5 days ago (look back only; never use shift(-n))
x.rolling(20, min_periods=15).mean() / .std() / .max()
x.pct_change(20, fill_method=None)
x.rank(axis=1, pct=True)         # daily rank across all stocks (0-1)
np.log(x)  x.where(x > 0)  x.clip(lower, upper)
# Winsorizing and standardization are handled by the system"""),
    "spwf.intro": L("对「选股回测」中当前设置的策略进行滚动优化：每个窗口仅使用过去的数据选取参数，并在随后的时段检验，逐段向前推进，得到完全样本外的表现。待优化的参数及取值范围可自行设定。",
                    "Walk-forward optimization of the strategy currently configured in Backtest: each window selects parameters using only past data and tests them on the following period, producing fully out-of-sample results. You choose which parameters to tune and which values to test."),
    "spwf.need_factors": L("请先在「选股回测」中选择至少一个因子。", "Please select at least one factor in Backtest first."),
    "spwf.using": L("当前策略", "Current strategy"),
    "spwf.need_reb": L("请至少选择一种调仓频率", "Please select at least one rebalance frequency"),
    "spwf.estimate": L("将划分为 {w} 个窗口；共 {n} 组参数，每组仅需完整回测一次", "{w} windows; {n} combinations, each backtested once over the whole period"),
    "spwf.progress_select": L("正在计算选股名单 {d}/{n}", "Building stock lists {d}/{n}"),
    "spwf.progress_bt": L("回测进度 {d}/{n}", "Backtesting {d}/{n}"),
    "spwf.note": L("灰色虚线表示参数切换时点。每组参数均自回测起始日持续运行，各测试期取所选参数对应资产曲线的收益进行拼接（延续持仓），切换参数时的调仓成本略有低估。",
                   "Dotted lines mark parameter changes. Every combination runs from the start date onward; each test period uses the returns from the selected combination's equity curve (positions carried over), so switching costs are slightly understated."),
    "spwf.latest": L("最新窗口选出的参数", "Parameters selected by the latest window"),
    "spwf.latest_note": L("若按此方法调参，接下来应采用的参数。", "The parameters this method would use going forward."),
    "spwf.apply": L("应用至选股回测", "Apply to Backtest"),
    "spwf.applied": L("已应用至「选股回测」", "Applied to Backtest"),
    "spwf.full": L("全区间各组参数表现（基于全部数据比较，非样本外结果，仅供参考）", "Each combination over the whole period (in-sample, for reference only)"),
    "spwf.stale": L("策略或区间已变更，以下为上次运行的结果。", "The strategy or date range has changed; the results below are from the previous run."),
    "sp.snapshots": L("成分股快照", "Constituent snapshots"),
    "sp.codes": L("涉及股票", "Stocks involved"),
    "sp.codes_help": L("区间内所有曾入选指数的股票（含已调出者），用于避免幸存者偏差",
                       "Every stock that was an index constituent during the period (including those later removed), to avoid survivorship bias"),
    "sp.downloaded": L("已下载", "Downloaded"),
    "sp.no_data": L("该股票池暂无数据，请先下载。", "No data for this universe yet. Please download it first."),
    "sp.workers": L("并行连接数", "Parallel connections"),
    "sp.workers_help": L("同时下载的连接数。连接过多可能被数据服务器断开，建议设为 4", "Number of simultaneous downloads. Too many may cause the data server to drop connections; 4 is recommended"),
    "sp.download_note": L("首次下载沪深300约需 8–10 分钟，数据量约 80 MB；此后仅增量更新最近几日数据。如下载中断，再次点击即可从断点继续。",
                          "The first download of CSI 300 takes about 8–10 minutes and about 80 MB; later updates fetch only the latest days. If the download is interrupted, click again to resume."),
    "sp.download": L("下载 / 更新数据", "Download / update data"),
    "sp.step_universe": L("正在获取历史成分股…", "Fetching historical constituents…"),
    "sp.step_index": L("正在获取指数及股票信息…", "Fetching index and stock information…"),
    "sp.step_stocks": L("正在下载 {n} 只股票的日线…", "Downloading daily bars for {n} stocks…"),
    "sp.download_errors": L("{n} 只股票下载失败，可稍后再次点击以补齐：", "{n} stocks failed to download. Click again later to complete them:"),
    "sp.download_done": L("完成：{n} 只股票数据均已更新至最新", "Done: {n} stocks up to date"),
    "sp.pack": L("数据包：导出 / 导入", "Data pack: export / import"),
    "sp.pack_note": L("将本机已下载的选股数据打包为 zip 文件，他人导入后即可直接使用，并可继续增量更新。分发前请确认数据源（BaoStock）的使用条款。",
                      "Package the downloaded selection data into a zip file that others can import, use directly and update incrementally. Please review the data source's (BaoStock) terms of use before distributing it."),
    "sp.pack_build": L("生成数据包", "Build data pack"),
    "sp.pack_building": L("正在打包…", "Packing…"),
    "sp.pack_download": L("下载数据包（约 {mb} MB）", "Download data pack (~{mb} MB)"),
    "sp.pack_import": L("导入数据包", "Import a data pack"),
    "sp.pack_import_btn": L("导入", "Import"),
    "sp.pack_imported": L("已导入 {n} 只股票的数据", "Imported data for {n} stocks"),
    "sp.loading_panel": L("正在整理数据…", "Preparing data…"),
    "sp.factor": L("因子", "Factor"),
    "sp.horizon": L("持有期（交易日）", "Holding period (days)"),
    "sp.horizon_help": L("因子值计算完成后，于下一交易日开盘买入并持有该天数的收益", "Return from the next open over this many trading days"),
    "sp.horizon_n": L("持有 {h} 天", "{h}-day holding"),
    "sp.groups": L("分组数", "Groups"),
    "sp.min_days": L("最短上市天数", "Minimum days listed"),
    "sp.min_days_help": L("排除新股：新股上市初期波动较大、估值不稳定", "Excludes new listings, which tend to be volatile with unstable valuations early on"),
    "sp.analyze": L("分析该因子", "Analyze factor"),
    "sp.analyzing": L("正在计算…", "Computing…"),
    "sp.overview": L("全部因子概览", "All factors overview"),
    "sp.overview_help": L("一次性计算全部因子的 IC 等指标，便于横向比较", "Compute IC statistics for every factor at once for comparison"),
    "sp.overview_title": L("全部因子概览（持有 {h} 天）", "All factors (holding {h} days)"),
    "sp.overview_note": L("IC 为正表示因子值越大、后续收益越高；为负则相反。|t 值| > 2 通常视为统计显著。",
                          "A positive IC means higher factor values were followed by higher returns; negative means the opposite. |t| > 2 is generally considered significant."),
    "sp.ic_mean": L("IC 均值", "Mean IC"),
    "sp.icir": L("ICIR（年化）", "ICIR (annual)"),
    "sp.t_stat": L("t 值", "t-stat"),
    "sp.ic_pos": L("IC>0 比例", "IC > 0 share"),
    "sp.mono": L("分组单调性", "Monotonicity"),
    "sp.suggest": L("建议方向", "Suggested direction"),
    "sp.ic_help": L("每期因子值与后续收益之间秩相关系数的平均值。在 A 股中，|IC| 达到 0.03 以上即可视为具有一定效果",
                    "Average rank correlation between the factor and subsequent returns. In A-shares, |IC| above about 0.03 is already meaningful"),
    "sp.icir_help": L("IC 均值 ÷ IC 标准差，用于衡量稳定性，数值越高越稳定", "Mean IC ÷ its standard deviation; higher values indicate a more consistent factor"),
    "sp.t_help": L("检验 IC 均值是否显著不为 0；绝对值大于 2 通常视为显著", "Tests whether mean IC differs significantly from zero; |t| > 2 is generally significant"),
    "sp.mono_help": L("各组年化收益是否随组号单调变化，+1 / -1 表示完全单调", "Whether group returns rise or fall steadily with the factor; ±1 is perfectly monotonic"),
    "sp.top_turnover": L("顶组换手", "Top-group turnover"),
    "sp.top_turnover_help": L("因子最高组每期被替换的成分比例；数值越高，交易成本越大", "Share of the top group replaced each period; higher values mean higher trading costs"),
    "sp.verdict_up": L("该因子在 {n} 期中表现显著且分组单调：因子值越大，后续收益越高。", "Across {n} periods this factor is significant and monotonic: higher values were followed by higher returns."),
    "sp.verdict_down": L("该因子在 {n} 期中表现显著且分组单调：因子值越小，后续收益越高（选股时请选择「越小越好」）。",
                         "Across {n} periods this factor is significant and monotonic: lower values were followed by higher returns (use \"lower is better\")."),
    "sp.verdict_weak": L("该因子在 {n} 期中效果不显著或分组不单调，单独使用时请谨慎。", "Across {n} periods this factor is not significant or not monotonic; use it on its own with caution."),
    # 第二期：财务因子 / 中性化 / IC 加权 / AI
    "sp.fin_downloaded": L("财务数据", "Financials"),
    "sp.fin_help": L("季度财务数据（ROE、毛利率、利润及营收增长、总股本），严格自首次公告日起生效，用于质量、成长及市值因子。沪深300首次下载约需 10 分钟",
                     "Quarterly financials (ROE, margins, profit and revenue growth, shares outstanding), effective strictly from the first announcement date; used by quality, growth and size factors. The first download for CSI 300 takes about 10 minutes"),
    "sp.with_fin": L("同时下载财务数据", "Also download financials"),
    "sp.with_div": L("同时下载分红送转数据", "Also download dividends"),
    "sp.div_downloaded": L("分红数据", "Dividends"),
    "sp.div_help": L("每次分红的除权除息日、每股现金分红及送股、转增比例，用于「现金分红并扣红利税」回测。沪深300首次下载约需 15 分钟",
                     "Ex-dates, cash per share, bonus and capitalization shares for each distribution; used by the \"cash dividends, taxed\" backtest option. First download for CSI 300 takes about 15 minutes"),
    "sp.step_div": L("正在下载 {n} 只股票的分红送转数据…", "Downloading dividends for {n} stocks…"),
    "sp.dividend": L("分红处理", "Dividends"),
    "sp.dividend_help": L("分红再投资：使用后复权价，分红全额再投资、不扣税（默认，与多数回测软件一致）。\n"
                          "现金分红并扣红利税：除息日现金到账，保留在账户中直至下次买入；卖出时按持股期限扣缴红利税"
                          "（≤1 个月 20%，1 个月至 1 年 10%，超过 1 年免税；送股按面值 1 元计税），与聚宽等平台及实盘一致。"
                          "高股息组合采用此方式时，年化收益通常低约 0.5 ~ 1 个百分点",
                          "Reinvest: back-adjusted prices; dividends fully reinvested, untaxed (default, like most backtesters).\n"
                          "Cash, taxed: cash arrives on the ex-date and waits until the next purchase; dividend tax is deducted "
                          "on sale by holding period (≤1 month 20%, up to 1 year 10%, over 1 year exempt; bonus shares taxed at "
                          "1 yuan par), matching JoinQuant and live trading. High-yield portfolios typically come out 0.5–1 pp/yr lower"),
    "sp.need_div": L("尚无分红数据，请先在「数据」页勾选「同时下载分红送转数据」后下载。",
                     "No dividend data yet. Download it on the Data tab with \"Also download dividends\" checked."),
    "sp.div_missing": L("{n} 只股票缺少分红数据，仍按分红再投资计算：{codes}",
                        "{n} stocks have no dividend data and are still treated as reinvesting: {codes}"),
    "sp.div_patched": L("BaoStock 分红表中缺失的除权除息已根据交易所除权参考价补齐：现金分红 {n} 次（每股金额，元：{eg}）；"
                        "配股等 {m} 次按全额参与处理（股数增加，不产生现金、不扣税）",
                        "Ex-dates missing from BaoStock's dividend table were filled in from the exchange reference prices: "
                        "{n} cash dividends (per share: {eg}); {m} rights issues etc. treated as fully taken up "
                        "(more shares, no cash, no tax)"),
    "m.dividend_cash": L("收到现金分红", "Cash dividends"),
    "m.dividend_tax": L("已扣红利税", "Dividend tax"),
    "sp.dividend_tax_help": L("仅统计已卖出的股票；回测结束时仍持有的股票，红利税于卖出时扣缴",
                              "Only for positions already sold; tax on stocks still held is deducted when they are sold"),
    "sp.step_fin": L("正在下载 {n} 只股票的财务数据…", "Downloading financials for {n} stocks…"),
    "sp.no_fin": L("尚未下载财务数据，质量、成长、市值类因子暂不可用（请在「数据」页勾选「同时下载财务数据」）。",
                   "Financial data has not been downloaded, so quality, growth and size factors are unavailable (select \"Also download financials\" on the Data tab)."),
    "sp.need_fin": L("所选因子需要财务数据，请先在「数据」页下载。", "The selected factor requires financial data. Please download it on the Data tab first."),
    "sp.neutral_industry": L("行业中性", "Industry neutral"),
    "sp.neutral_industry_help": L("剔除因子中的行业成分，仅在同行业内比较相对高低，避免选股集中于少数行业（行业采用当前证监会分类）",
                                  "Removes industry effects so stocks are compared within their industry and picks are not concentrated in a few industries (uses the current CSRC classification)"),
    "sp.neutral_size": L("市值中性", "Size neutral"),
    "sp.neutral_size_help": L("剔除因子中的市值成分，避免因子仅成为小盘股效应的替代（需要财务数据）",
                              "Removes size effects so the factor is not merely a small-cap proxy (requires financial data)"),
    "sp.corr": L("因子相关性", "Factor correlation"),
    "sp.corr_note": L("两个因子高度相关时，同时使用相当于重复押注；选择各自有效且相关性较低的因子进行组合，效果更佳。",
                      "Highly correlated factors amount to the same bet; combining factors that are each effective and weakly correlated works better."),
    "sp.corr_run": L("计算相关性", "Compute correlation"),
    "chart.corr": L("相关系数", "Correlation"),
    "sp.weighting": L("因子加权方式", "Factor weighting"),
    "sp.weighting_help": L("手动：按所设定的方向与权重。IC / ICIR 加权：根据各因子过去一段时间的实际预测能力自动确定权重与方向，仅使用当时已知的数据",
                           "Manual uses your directions and weights. IC / ICIR weighting derives weights and directions from each factor's recent predictive power, using only data available at the time"),
    "sp.lookback": L("回看期（交易日）", "Lookback (days)"),
    "sp.lookback_help": L("计算 IC 权重时参考的历史长度", "History used to compute IC weights"),
    "sp.ic_fallback_note": L("历史数据不足时（起始阶段），暂按手动设定的方向与权重。", "Until sufficient history is available, the manual directions and weights are used."),
    "sp.industry_mix": L("行业分布", "Industry mix"),
    "sp.ai": L("以自然语言描述选股规则（AI）", "Describe your stock selection in plain language (AI)"),
    "sp.ai_placeholder": L("例如：每月从沪深300中选取 20 只估值低、ROE 高、近期跌幅较大的股票，行业需分散",
                           "e.g. Each month select 20 CSI 300 stocks with low valuations, high ROE and recent declines, diversified across industries"),
    "sp.ai_apply": L("填入下方设置", "Fill in the settings below"),
    "sp.dl_start_help": L("建议比计划的回测起点早一年，额外的数据用于因子预热", "Start about one year before the planned backtest start; the extra history is used to warm up the factors"),
    "sp.warmup_note": L("回测自数据首日开始时，前两至三个月将用于积累因子所需的历史数据（如 60 日波动率），期间不会选股。将开始日期后移，或下载更早的数据即可避免。",
                        "When the backtest starts on the first day of data, the first 2–3 months are used to build factor history (e.g. 60-day volatility) and no stocks are selected. Move the start date later or download earlier data to avoid this."),
    "sp.load_saved": L("载入已保存的选股策略", "Load a saved selection strategy"),
    "sp.factor_setup": L("因子与权重", "Factors & weights"),
    "sp.pick_factors": L("选择因子（可多选）", "Factors (multiple selection)"),
    "sp.weight": L("权重", "Weight"),
    "sp.direction": L("方向", "Direction"),
    "sp.factor_note": L("各因子先按日去极值、标准化，再按方向与权重加总为综合得分。", "Each factor is winsorized and standardized daily, then combined by direction and weight into a composite score."),
    "sp.rules": L("选股与调仓", "Selection & rebalancing"),
    "sp.top_n": L("持有股票数", "Number of stocks"),
    "sp.rebalance": L("调仓频率", "Rebalance"),
    "sp.every_n": L("每 N 个交易日", "Every N trading days"),
    "sp.every_n_days": L("N", "N"),
    "sp.exclude_st": L("排除 ST 股", "Exclude ST stocks"),
    "sp.name_ph": L("例如：沪深300 低估值 + 反转", "e.g. CSI 300 value + reversal"),
    "sp.running": L("正在回测…（股票数量较多时需数十秒）", "Running… (may take tens of seconds with many stocks)"),
    "sp.took": L("用时 {s} 秒", "took {s}s"),
    "sp.turnover_help": L("每年卖出金额 ÷ 平均资产。1× 表示组合每年约完整换手一次", "Annual sell value ÷ average assets; 1× means the portfolio turns over about once a year"),
    "sp.n_rebalances": L("调仓次数", "Rebalances"),
    "sp.bench_label": L("基准（{name}指数）", "Benchmark ({name} index)"),
    "sp.tab_holdings": L("每期选股", "Picks per period"),
    "sp.picked": L("入选股票", "Selected stocks"),
    "sp.skipped": L("有 {n} 个调仓日因可选股票不足（因子计算需要历史数据）而跳过", "{n} rebalance dates were skipped due to insufficient eligible stocks (factors require history)"),
    "chart.ic_roll": L("{n} 期滚动均值", "{n}-period rolling mean"),
    "chart.group": L("第 {g} 组", "Group {g}"),
    "chart.group_low": L("（因子最小）", " (lowest)"),
    "chart.group_high": L("（因子最大）", " (highest)"),
    "chart.long_short": L("多空（最大组 − 最小组）", "Long-short (top − bottom)"),
    "chart.nav": L("累计净值", "Cumulative value"),
    "chart.annual": L("年化收益", "Annualized return"),

    # ---- 模拟盘 ----
    "nav.paper": L("6. 模拟盘", "6. Paper trading"),
    "nav.go_paper": L("前往模拟盘", "Go to Paper trading"),
    "pp.intro": L("基于已保存的策略开设模拟账户：每个交易日收盘后更新数据，按与回测相同的规则推进账户，并给出下一交易日开盘需执行的交易。无需券商账户。",
                  "Open a simulated account for a saved strategy: after each close it updates data, advances the account using the same rules as the backtest, and lists the trades for the next open. No brokerage account required."),
    "pp.new": L("新建模拟账户", "New paper account"),
    "pp.kind": L("策略类型", "Strategy type"),
    "pp.kind_single": L("单标的 / 择时策略", "Single-asset / timing"),
    "pp.kind_selection": L("多因子选股", "Multi-factor selection"),
    "pp.assets": L("标的（从本地数据库中选择日线数据）", "Assets (daily data from the local library)"),
    "pp.assets_help": L("模拟盘将自动重新下载这些标的的前复权日线，确保最新价格与实际价格一致", "The account downloads its own forward-adjusted daily bars so the latest prices match actual prices"),
    "pp.no_daily_data": L("本地数据库中暂无 AKShare / BaoStock 日线数据，请先在「1. 数据」页面下载。", "No AKShare / BaoStock daily data in the local library yet. Please download some on the \"1. Data\" page."),
    "pp.no_selection": L("暂无已保存的多因子选股策略，请先在「5. 多因子选股」中保存。", "No saved selection strategy yet. Please save one on \"5. Stock selection\" first."),
    "pp.selection_strategy": L("选股策略", "Selection strategy"),
    "pp.need_universe": L("{name} 的数据尚未下载，请先在「5. 多因子选股」的数据页下载。", "{name} data has not been downloaded. Please download it on the Data tab of \"5. Stock selection\"."),
    "pp.start_mode": L("开始方式", "Start"),
    "pp.start_now": L("从最新数据开始（实时模拟）", "From the latest data (live paper trading)"),
    "pp.start_past": L("从历史某日开始（先回补历史记录）", "From a past date (backfill history)"),
    "pp.start_date": L("开始日期", "Start date"),
    "pp.start_date_help": L("自该日收盘起产生信号，于下一交易日开盘首次成交", "Signals start from this day's close; the first fills occur at the next open"),
    "pp.name": L("账户名称", "Account name"),
    "pp.name_ph": L("例如：沪深300 低估值 月度调仓", "e.g. CSI 300 value monthly"),
    "pp.create": L("创建模拟账户", "Create paper account"),
    "pp.account": L("模拟账户", "Account"),
    "pp.paused": L("已暂停", "paused"),
    "pp.running": L("正在更新数据并运行…", "Updating data and running…"),
    "pp.run_done": L("完成：成功 {ok} 个，失败 {failed} 个", "Done: {ok} succeeded, {failed} failed"),
    "pp.run_this": L("更新并运行", "Update & run"),
    "pp.run_all": L("更新全部账户", "Update all accounts"),
    "pp.pause": L("暂停", "Pause"),
    "pp.resume": L("恢复", "Resume"),
    "pp.delete": L("删除", "Delete"),
    "pp.delete_confirm": L("确定删除「{name}」？账本及历史记录将一并删除，且无法恢复。", "Delete \"{name}\"? Its ledger and history will be permanently removed."),
    "pp.delete_yes": L("确定删除", "Delete permanently"),
    "pp.stale": L("数据截至 {through}，最新应为 {expected}。请点击「更新并运行」获取最新数据并生成信号；若刚运行后仍显示此提示，说明数据源尚未发布当日数据（通常在 18:00 后），请稍后重试。",
                  "Data runs through {through}; the latest should be {expected}. Click \"Update & run\" to fetch it. If this message remains after a run, the source has not yet published today's data (usually after 18:00); please try again later."),
    "pp.divergence": L("使用最新数据重放时，得到的历史成交与账本记录不完全一致（通常因数据修订或复权口径变化）。账本保持不变，后续交易将基于最新数据计算。",
                       "Replaying on the latest data produced past fills that differ slightly from the ledger (usually due to revised or re-adjusted data). The ledger is kept unchanged; future trades use the latest data."),
    "pp.not_run": L("该账户尚未运行，请点击「更新并运行」。", "This account has not run yet. Click \"Update & run\"."),
    "pp.value": L("总资产", "Total value"),
    "pp.total_return": L("累计收益", "Total return"),
    "pp.day_pnl": L("最近一日盈亏", "Last day P&L"),
    "pp.n_positions": L("持仓数", "Positions"),
    "pp.data_through": L("数据截至", "Data through"),
    "pp.execute_on": L("信号执行日", "Signals execute on"),
    "pp.execute_on_help": L("以下信号将于该日开盘执行（依据交易日历，已考虑节假日）", "The signals below execute at this day's open (per the trading calendar, holidays included)"),
    "pp.meta": L("开始日期 {start} · 创建于 {created} · 上次运行 {last_run}", "Started {start} · created {created} · last run {last_run}"),
    "pp.not_started": L("尚未到开始日期", "not started yet"),
    "pp.tab_signals": L("今日信号", "Signals"),
    "pp.tab_positions": L("持仓", "Positions"),
    "pp.tab_nav": L("资产曲线", "Equity"),
    "pp.tab_fills": L("成交记录", "Fills"),
    "pp.signals_title": L("{date} 开盘待执行交易", "Trades for the {date} open"),
    "pp.no_signals": L("下一交易日无待执行交易。", "No trades for the next trading day."),
    "pp.signals_note": L("股数按最新收盘价估算，实际按开盘价成交（与回测一致）。停牌或开盘涨停时的买入、跌停时的卖出将无法成交。导出的 CSV 可用于在券商端手动下单。",
                         "Share counts are estimated from the latest close; actual fills use the open (as in the backtest). Buys during suspension or at limit-up and sells at limit-down will not fill. The exported CSV can be used to place orders manually with your broker."),
    "pp.col_code": L("代码", "Code"),
    "pp.col_name": L("名称", "Name"),
    "pp.col_shares": L("股数", "Shares"),
    "pp.col_ref_price": L("参考价", "Ref. price"),
    "pp.col_est_value": L("预计金额", "Est. value"),
    "pp.col_reason": L("理由", "Reason"),
    "pp.col_cost": L("成本价", "Cost"),
    "pp.col_price": L("最新价", "Price"),
    "pp.col_value": L("市值", "Value"),
    "pp.col_pnl": L("浮动盈亏", "Unrealized P&L"),
    "pp.col_weight": L("仓位", "Weight"),
    "pp.download_signals": L("下载信号（CSV）", "Download signals (CSV)"),
    "pp.download_positions": L("下载持仓（CSV）", "Download positions (CSV)"),
    "pp.no_positions": L("当前无持仓。", "No positions."),
    "pp.cash": L("可用现金：{cash} 元", "Cash: {cash}"),
    "pp.dividends": L("自开始日起累计收到现金分红 {cash} 元（税前），已扣红利税 {tax} 元",
                      "Since the start date: cash dividends {cash} (pre-tax), dividend tax {tax}"),
    "pp.nav_soon": L("运行数个交易日后，此处将显示资产曲线。", "The equity curve will appear after a few trading days."),
    "pp.no_fills": L("暂无成交。", "No fills yet."),
    "pp.schedule": L("每日自动运行（Windows 任务计划程序）", "Run automatically every day (Windows Task Scheduler)"),
    "pp.schedule_note": L("每周一至周五在设定时间自动更新数据并推进全部模拟账户（建议设为 19:00 左右；经实测，18:40 时当日数据已发布）。运行时计算机需保持开机，错过的交易日将在下次运行时自动补齐。日志保存于 data_cache\\paper\\daily.log。",
                          "Updates data and advances all accounts Monday to Friday at the set time (around 19:00 is recommended; in testing, the day's data was available by 18:40). The computer must be on; missed days are caught up on the next run. Log file: data_cache\\paper\\daily.log."),
    "pp.task_on": L("✅ 已设置每日自动运行", "✅ Daily run is scheduled"),
    "pp.task_off": L("尚未设置自动运行", "Not scheduled"),
    "pp.task_time": L("运行时间", "Run at"),
    "pp.task_create": L("创建定时任务", "Create schedule"),
    "pp.task_update": L("更新运行时间", "Update time"),
    "pp.task_delete": L("删除定时任务", "Remove schedule"),
    "pp.log": L("最近运行日志", "Recent log"),
    "home.s6": L("6. 模拟盘", "6. Paper trading"),
    "home.s6_body": L("将策略接入模拟账户：每日收盘后自动推进，给出次日开盘的交易信号，并可导出 CSV 用于手动下单。",
                      "Run strategies in a simulated account that advances after each close, lists trades for the next open and exports them to CSV for manual orders."),
    "home.s6_note": L("与回测采用同一套规则，逐日推进的结果与回测一致", "Same rules as the backtest; day-by-day results match it exactly"),
    "paper.divergence": L("与账本不一致", "differs from ledger"),

    # ---- 模型设置 ----
    "nav.settings": L("AI 模型设置", "AI model settings"),
    "nav.go_settings": L("前往模型设置", "Go to AI model settings"),
    "set.intro": L("用于「自然语言描述（AI）」及「AI 解读结果」功能。支持 Claude、OpenAI、各类兼容 OpenAI 协议的服务（DeepSeek、通义千问、Kimi、智谱、本地 Ollama）以及 LiteLLM。",
                   "Used by \"Describe in plain language (AI)\" and \"Explain with AI\". Supports Claude, OpenAI, OpenAI-compatible services (DeepSeek, Qwen, Kimi, Zhipu, local Ollama) and LiteLLM."),
    "set.preset": L("快速选择", "Preset"),
    "set.provider": L("接口类型", "Interface"),
    "set.model": L("模型名称", "Model"),
    "set.model_ph_anthropic": L("例如：claude-opus-5-5", "e.g. claude-opus-5-5"),
    "set.model_ph_openai": L("请参照服务商文档填写模型名称", "Model name from your provider's documentation"),
    "set.model_ph_litellm": L("例如：deepseek/deepseek-chat、anthropic/claude-opus-5-5", "e.g. deepseek/deepseek-chat, anthropic/claude-opus-5-5"),
    "set.model_help": L("模型名称可能随服务商更新而变化，请以服务商文档为准", "Model names may change over time; refer to your provider's documentation"),
    "set.api_key": L("API Key", "API key"),
    "set.api_key_help": L("使用本地 Ollama 时可不填", "Not required for local Ollama"),
    "set.api_key_help_env": L("留空时将读取环境变量 {env}", "Leave empty to use the {env} environment variable"),
    "set.base_url": L("接口地址（可选）", "Base URL (optional)"),
    "set.base_url_ph": L("留空则使用官方地址", "Leave empty for the official endpoint"),
    "set.base_url_help": L("使用代理、中转或兼容服务时填写", "Required for proxies, relays or compatible services"),
    "set.json_mode": L("结构化输出方式", "Structured output"),
    "set.json_mode_help": L("生成策略时要求模型输出固定格式的 JSON。若服务不支持 JSON Schema，请改用「JSON 模式」；仍报错时请选择「仅提示词」。",
                            "How the model is instructed to return JSON when generating strategies. If the service does not support JSON Schema, use JSON mode; if errors persist, use prompt only."),
    "set.timeout": L("超时时间（秒）", "Timeout (s)"),
    "set.fallback": L("拒答时自动切换模型", "Fallback on refusal"),
    "set.fallback_help": L("Claude 官方接口功能：当模型因安全策略拒绝回答时，由服务端自动切换至其他模型重试",
                           "Claude API feature: if the model declines for policy reasons, the server retries with another model"),
    "set.litellm_hint": L("LiteLLM 的模型名称需带服务商前缀；API Key 也可通过各服务商对应的环境变量提供。",
                          "LiteLLM model names include a provider prefix; API keys can also be supplied through each provider's environment variable."),
    "set.about": L("关于 SimpleQuant", "About SimpleQuant"),
    "set.version": L("版本 {v}", "Version {v}"),
    "set.data_dir": L("数据目录：{path}", "Data folder: {path}"),
    "upd.check": L("检查更新", "Check for updates"),
    "upd.auto": L("启动时自动检查更新", "Check for updates at startup"),
    "upd.checking": L("正在检查更新……", "Checking for updates…"),
    "upd.latest": L("当前已是最新版本（{v}）。", "You are running the latest version ({v})."),
    "upd.available": L("发现新版本 {v}，需下载约 {mb} MB。", "Version {v} is available ({mb} MB to download)."),
    "upd.available_full": L("发现新版本 {v}，本次需下载完整安装包（约 {mb} MB）。",
                            "Version {v} is available. This update requires the full installer ({mb} MB)."),
    "upd.available_source": L("发现新版本 {v}。当前以源码方式运行，请使用 git pull 获取更新。",
                              "Version {v} is available. You are running from source; update with git pull."),
    "upd.download": L("下载更新", "Download update"),
    "upd.downloading": L("正在下载新版本 {v}：{done} / {total} MB", "Downloading version {v}: {done} / {total} MB"),
    "upd.ready": L("新版本 {v} 已下载完成，重启 SimpleQuant 后即可完成更新。",
                   "Version {v} has been downloaded. Restart SimpleQuant to finish updating."),
    "upd.restart": L("立即重启并更新", "Restart and update"),
    "upd.restarting": L("正在退出并安装更新，完成后将自动重新打开 SimpleQuant。",
                        "Exiting to install the update. SimpleQuant will reopen automatically."),
    "upd.later": L("稍后", "Later"),
    "upd.notes": L("更新说明", "Release notes"),
    "upd.page": L("前往发布页面", "Open the releases page"),
    "upd.err_network": L("无法连接 GitHub，请稍后重试，或前往发布页面手动下载安装包。",
                         "Unable to reach GitHub. Try again later, or download the installer from the releases page."),
    "upd.err_verify": L("更新文件校验未通过，已停止更新。请前往发布页面手动下载安装包。",
                        "The update failed verification and was not installed. Please download the installer from the releases page."),
    "upd.err_other": L("检查更新时出错：{detail}", "Update check failed: {detail}"),
    "upd.done": L("已更新至版本 {v}。", "Updated to version {v}."),
    "upd.failed": L("上次更新未能完成，已保留原版本（{detail}）。可前往设置页重新检查更新，或在发布页面手动下载安装包。",
                    "The last update could not be completed and the previous version was kept ({detail}). Check for updates again in Settings, or download the installer from the releases page."),
    "upd.failed_busy": L("上次更新未能完成：SimpleQuant 未能在 90 秒内完全退出（可能有模拟盘定时任务正在运行），程序文件未作任何改动。",
                         "The last update was not applied: SimpleQuant did not exit within 90 seconds (a scheduled paper-trading run may have been active). No program files were changed."),
    "set.save": L("保存", "Save"),
    "set.saved": L("已保存至 {path}", "Saved to {path}"),
    "set.test": L("测试连接", "Test connection"),
    "set.testing": L("正在连接…", "Connecting…"),
    "set.test_ok": L("连接成功，模型回复：{reply}", "Connected. Model replied: {reply}"),
    "set.storage": L("设置（包括 API Key）以明文形式保存在本机 {path}，不会上传至任何服务器，也不位于项目文件夹内。",
                     "Settings (including the API key) are stored in plain text at {path} on this computer only. They are never uploaded and are kept outside the project folder."),

    # ---- 新界面（NiceGUI） ----
    "gui.cancel": L("取消", "Cancel"),
    "mig.title": L("导入旧版数据", "Import data from the source version"),
    "mig.body": L("已找到 SimpleQuant 源码版的数据目录（约 {mb} MB），包括行情数据、选股数据、模拟账户、已保存的策略及自定义因子。"
                  "导入时将复制到本程序的数据目录，原目录保持不变。",
                  "Found the data folder of the SimpleQuant source version (about {mb} MB): market data, stock data, paper "
                  "accounts, saved strategies and custom factors. Importing copies them into this program's data folder; "
                  "the old folder is left unchanged."),
    "mig.dir": L("旧版目录（包含 data_cache 的文件夹）", "Old folder (the one containing data_cache)"),
    "mig.go": L("导入", "Import"),
    "mig.skip": L("不再提示", "Don't ask again"),
    "mig.done": L("已导入 {n} 个文件", "Imported {n} files"),
    "gui.available": L("可选范围 {lo} ~ {hi}", "Available {lo} ~ {hi}"),
    "gui.theme": L("切换主题：跟随系统 / 浅色 / 深色", "Theme: system / light / dark"),

    # ---- 界面改版（2026-09-30，样稿 D：流程步骤条 + 研究报告风格） ----
    "flow.timing": L("择时策略", "Timing"),
    "flow.selection": L("多因子选股", "Stock selection"),
    "step.data": L("数据", "Data"),
    "step.strategy": L("策略", "Strategy"),
    "step.backtest": L("回测", "Backtest"),
    "step.optimize": L("优化", "Optimize"),
    "step.selection": L("选股", "Selection"),
    "step.paper": L("模拟盘", "Paper"),
    "step.not_started": L("未开始", "Not started"),
    "step.done": L("已完成", "Done"),
    "step.n_data": L("{n} 份数据", "{n} dataset(s)"),
    "step.n_saved": L("已保存 {n} 个", "{n} saved"),
    "step.n_accounts": L("{n} 个账户", "{n} account(s)"),
    "step.eyebrow": L("{flow} · 第 {n} 步", "{flow} · Step {n}"),
    "top.settings": L("AI 模型", "AI model"),

    "home.greet_morning": L("早上好", "Good morning"),
    "home.greet_afternoon": L("下午好", "Good afternoon"),
    "home.greet_evening": L("晚上好", "Good evening"),
    "home.status": L("本地数据截至 {d} · {n} 份数据 · {s} 个策略", "Local data through {d} · {n} datasets · {s} strategies"),
    "home.status_empty": L("本地尚无数据", "No local data yet"),
    "home.hero_eyebrow": L("A 股 · ETF 策略回测", "A-SHARE · ETF BACKTESTING"),
    "home.hero_title": L("把交易想法，|变成可以检验的结论。", "Turn trading ideas|into conclusions you can test."),
    "home.hero_body": L("无需编程。选择数据，用模板、条件组件、自然语言或 Python 代码描述策略，几秒钟即可得到一份完整的回测报告——收益、回撤、每一笔成交，都按 A 股真实规则计算。",
                        "No coding required. Pick your data, describe a strategy with a template, rule blocks, plain language or Python, and get a complete backtest report in seconds — returns, drawdowns and every trade, all under real A-share rules."),
    "home.start_first": L("开始第一次回测", "Run your first backtest"),
    "home.get_data_first": L("先获取数据", "Get data first"),
    "home.continue": L("继续上次的工作", "Pick up where you left off"),
    "home.suggest_next": L("建议下一步", "Suggested next"),
    "home.open_report": L("打开回测报告", "Open the report"),
    "home.try_optimize": L("检验其他参数组合", "Test other parameters"),
    "home.to_paper": L("放入模拟盘", "Start paper trading"),
    "home.new_work": L("开始新的工作", "Start something new"),
    "home.new_work_note": L("四种方式，任选其一", "Four ways to begin"),
    "home.w_template": L("从模板开始", "Start from a template"),
    "home.w_template_body": L("双均线、RSI、布林带、动量轮动等内置策略，调整参数即可得到第一份报告。",
                              "Moving-average cross, RSI, Bollinger bands, momentum rotation and more — tune the parameters and run."),
    "home.w_template_more": L("最快，约 1 分钟", "Fastest, about a minute"),
    "home.w_ai": L("用自然语言描述", "Describe it in words"),
    "home.w_ai_body": L("例如「MACD 金叉且 RSI 低于 70 时买入，亏损 8% 止损」，由 AI 转换为交易规则。",
                        "e.g. \"Buy when MACD crosses up and RSI is below 70; stop out at an 8% loss\" — AI turns it into rules."),
    "home.w_ai_more": L("需要设置 AI 模型", "Requires an AI model"),
    "home.w_code": L("编写代码", "Write Python"),
    "home.w_code_body": L("编写 Python 策略类，整手、T+1、交易费用照常计算，参数可直接用于优化。",
                          "Write a Python strategy class; board lots, T+1 and costs still apply, and parameters can be optimized."),
    "home.w_code_more": L("适合熟悉 Python 的用户", "For Python users"),
    "home.w_selection": L("多因子选股", "Multi-factor selection"),
    "home.w_selection_body": L("在沪深300、中证500 成分股中按价值、动量等因子定期选股、调仓。",
                               "Pick stocks from the CSI 300 / CSI 500 by value, momentum and other factors, rebalancing on a schedule."),
    "home.w_selection_more": L("组合策略", "Portfolio strategy"),
    "home.recent": L("最近的报告", "Recent reports"),
    "home.recent_note": L("点击可重新打开", "Click to reopen"),
    "home.sharpe": L("夏普 {v}", "Sharpe {v}"),
    "home.paper_title": L("模拟账户 · {name}", "Paper account · {name}"),
    "home.paper_none": L("尚未创建模拟账户。策略回测满意后，可放入模拟盘逐日跟踪。",
                         "No paper accounts yet. Once a backtest looks good, track it day by day in paper trading."),
    "home.paper_create": L("新建模拟账户 →", "Create a paper account →"),
    "home.paper_view": L("查看信号 →", "View signals →"),
    "home.paper_through": L("数据截至 {d}", "Data through {d}"),
    "home.paper_waiting": L("尚未运行", "Not run yet"),
    "home.paper_more": L("另有 {n} 个账户", "{n} more accounts"),

    "bt.setup": L("回测设置", "Backtest setup"),
    "bt.edit_setup": L("修改设置", "Edit setup"),
    "bt.chip_data": L("数据", "Data"),
    "bt.chip_strategy": L("策略", "Strategy"),
    "bt.chip_range": L("区间", "Period"),
    "bt.chip_broker": L("资金与费率", "Capital & costs"),
    "bt.cash_wan": L("{v} 万元", "¥{v}0k"),
    "bt.report_eyebrow": L("择时策略 · 回测报告 · {time}", "Timing strategy · Backtest report · {time}"),
    "bt.span_ym": L("约 {y} 年 {m} 个月", "about {y} years {m} months"),
    "bt.span_y": L("约 {y} 年", "about {y} years"),
    "bt.span_m": L("约 {m} 个月", "about {m} months"),
    "bt.span_d": L("{d} 天", "{d} days"),
    "bt.lede": L("在{span}的回测期内，该策略累计收益 <em>{ret}</em>，年化 <em>{cagr}</em>；同期买入并持有的收益为 <em>{bench}</em>。最大回撤 <em>{dd}</em>（买入持有为 {bdd}），共完成 {n} 笔交易。",
                 "Over a backtest period of {span}, the strategy returned <em>{ret}</em> in total, <em>{cagr}</em> annualized; buy-and-hold returned <em>{bench}</em> over the same period. Maximum drawdown was <em>{dd}</em> (buy-and-hold: {bdd}), with {n} completed trades."),
    "bt.lede_beat": L("策略跑赢买入持有 {v} 个百分点。", "The strategy beat buy-and-hold by {v} percentage points."),
    "bt.lede_lag": L("策略跑输买入持有 {v} 个百分点。", "The strategy trailed buy-and-hold by {v} percentage points."),
    "bt.lede_calmer": L("回撤小于买入持有，走势更平稳。", "Its drawdown was smaller than buy-and-hold, so the ride was smoother."),
    "bt.lede_rougher": L("回撤大于买入持有，需要承受更大的波动。", "Its drawdown was larger than buy-and-hold, so expect a bumpier ride."),
    "bt.fig1": L("图 1", "Figure 1"),
    "bt.fig2": L("图 2", "Figure 2"),
    "bt.fig1_caption": L("资产曲线与回撤。实线为策略，虚线为买入持有基准。", "Equity and drawdown. Solid line: strategy; dotted line: buy-and-hold benchmark."),
    "bt.fig2_caption": L("价格与买卖点。▲ 买入，▼ 卖出。", "Price with trades. ▲ buy, ▼ sell."),
    "bt.details": L("交易明细", "Trade details"),
    "bt.next": L("下一步", "Next steps"),
    "bt.next_opt": L("参数优化 →", "Optimize parameters →"),
    "bt.next_opt_body": L("批量检验参数组合，并留出样本外数据，确认结果并非过拟合", "Test many parameter combinations and hold out data to check for overfitting"),
    "bt.next_paper": L("放入模拟盘", "Paper trade it"),
    "bt.next_paper_body": L("每日收盘后自动运行，给出次日开盘的交易信号", "Runs after each close and gives next-open trade signals"),
    "bt.next_export": L("导出到其他平台", "Export to other platforms"),
    "bt.next_export_body": L("导出 Python 脚本，或到聚宽 / 掘金 / QMT 上复核结果", "Export a Python script, or double-check on JoinQuant / MyQuant / QMT"),
    "bt.next_ai_body": L("由 AI 用文字解读本次结果", "Let AI explain these results in words"),
    "bt.recent_trades": L("最近平仓", "Recent closed trades"),
    "bt.trade_line": L("{d} 平仓", "Closed {d}"),
    "bt.no_closed": L("本次回测没有已平仓的交易", "No closed trades in this backtest"),
})
